# Generated by Django 6.0.4 on 2026-04-25 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='epe_reason',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='incident',
            name='epe_score',
            field=models.FloatField(default=0.0),
        ),
    ]
